import type { Locale } from "@/lib/i18n";

/**
 * Owner-portal copy (B6). Arabic strings are verbatim from docs/design-specs/B6-debtor-journey.md where the
 * design draws them; the rest follows the same humane, second-person tone. English mirrors the Arabic.
 * Server-authored text (next-step bodies, document statuses, messages) stays Arabic in both locales.
 */
const ar = {
  unit: "ريال",
  back: "رجوع",
  backHome: "العودة للرئيسية",
  needHelp: "أحتاج مساعدة",
  tryAgain: "إعادة المحاولة",
  sending: "جارٍ الإرسال",
  networkError: "تعذّر الاتصال. تحقق من الإنترنت ثم حاول مرة أخرى — لم يُفقد شيء مما كتبته.",
  offlineError: "أنت غير متصل بالإنترنت الآن. حاول مرة أخرى عند عودة الاتصال.",
  genericError: "حدث خطأ غير متوقع. حاول مرة أخرى بعد قليل.",
  optional: "(اختياري)",
  close: "إغلاق",
  daysLeft: (n: string) => `(${n})`,

  home: {
    title: "الرئيسية",
    nextStepEyebrow: "خطوتك التالية",
    until: "لديك حتى",
    today: "(اليوم)",
    passed: "انتهت المهلة — تواصل مع مسؤول حالتك وسنساعدك",
    nothingTitle: "لا شيء مطلوب منك الآن",
    nothingBody: "سنخبرك فور وجود خطوة جديدة. يمكنك مراسلة مسؤول حالتك في أي وقت.",
    progressTitle: "أين وصلت حالتك",
    allStages: "كل المراحل",
    progressLabel: (cur: number, total: number, label: string) => `${cur} من ${total} · ${label}`,
    docsTile: "المستندات",
    debtTile: "المديونية",
    message: (name: string) => `مراسلة ${name}`,
    messageShort: "مراسلة",
    noManager: "سيُسند إليك مسؤول حالة قريباً. يمكنك مراسلتنا الآن.",
    messages: "الرسائل",
    switchLanguage: "English",
    /** Server titles/CTAs are Arabic; the English UI localizes them by `nextStep.type`. */
    localizeNext: false,
    nextTitles: { offer: "راجع العرض الجديد", document: "ارفع المستند المطلوب", agreement: "سجّلنا موافقتك", payment: "القسط القادم", closed: "أُغلقت حالتك" },
    nextCtas: { offer: "عرض التفاصيل", document: "المستندات", agreement: "تفاصيل الاتفاق", payment: "المدفوعات", closed: "مستندات الإغلاق" },
    docsNeed: (n: number) => `${n} يحتاج رفعاً`,
    docsDone: "كلها مكتملة",
    debtSub: "تفصيل واضح",
    managerRole: "مسؤولة حالتك",
    appointmentCall: "مكالمتكم",
    appointmentVisit: "موعدكم",
  },

  journey: { title: "مراحل حالتك", now: "الآن" },

  docs: {
    title: "المستندات المطلوبة",
    subRejected: (n: number) => `${n} يحتاج رفعاً من جديد`,
    subNeeded: (n: number) => `${n} يحتاج رفعاً`,
    subDone: "كلها مكتملة",
    whyAgain: "لماذا نحتاجه مرة أخرى؟",
    until: "حتى",
    requestedBy: (by: string) => `طلبه ${by}`,
    upload: "رفع ملف",
    camera: "تصوير",
    help: "أحتاج مساعدة في هذا المستند",
    helpSent: "وصل طلبك إلى مسؤول حالتك، وسيتواصل معك في الرسائل.",
    openMessages: "فتح الرسائل",
    uploading: "جارٍ الرفع",
    uploaded: (title: string) => `رفعنا «${title}». حالته الآن: قيد المراجعة.`,
    tooLarge: "حجم الملف أكبر من 20 ميغابايت. جرّب ملفاً أصغر أو صورة أوضح بحجم أقل.",
    fileHint: "PDF أو صورة، حتى 20 ميغابايت.",
    emptyTitle: "لا مستندات مطلوبة منك الآن",
    emptyBody: "سنخبرك إذا احتجنا أي مستند، مع السبب والمهلة.",
    closureLink: "مستندات الإغلاق",
  },

  debt: {
    title: "ما عليك الآن",
    total: "المبلغ المتبقي على التمويل",
    report: "أعتقد أن هناك خطأ في المبلغ",
    emptyTitle: "لم تصلنا أرقام المديونية بعد",
    emptyBody: "ستظهر هنا بعد أن يرسلها المصرف، مع تاريخ التحديث وشرح لكل بند.",
  },

  options: {
    title: "الخيارات المتاحة لك",
    details: "عرض التفاصيل",
    others: "خيارات أخرى يمكنك السؤال عنها",
    noOffer: "لا يوجد عرض مقدَّم لك الآن. سيظهر هنا عندما يرسله المصرف، ويمكنك السؤال عن أي خيار في الأسفل.",
    inquiryNote: "السؤال لا يعني التزاماً بأي خيار.",
  },

  offer: {
    title: "العرض المقدم لك",
    validUntil: "صالح حتى",
    heroInstallment: "قسطك الجديد",
    heroPayoff: "المبلغ المطلوب",
    heroSub: (day: number, months: number) => `يوم ${day} من كل شهر · ${months} شهراً`,
    heroPayoffSub: "دفعة واحدة وتنتهي المديونية",
    starts: "يبدأ",
    ends: "ينتهي",
    lateFees: "غرامات التأخير",
    waived: (amount: string) => `تُلغى (${amount} ريال)`,
    home: "بيتك",
    homeStays: "يبقى ملكك",
    whatIfLate: "ماذا لو تأخرت عن قسط؟",
    lateBody: (missed: string, cure: string) =>
      `نتواصل معك أولاً. إذا تأخر ${missed} نمنحك ${cure} للتصحيح ونبحث معك عن حل، قبل أي خطوة أخرى.`,
    missedTwo: "قسطان متتاليان",
    missedN: (n: number) => `${n} أقساط متتالية`,
    missedOne: "قسط واحد",
    reviewAccept: "مراجعة وقبول",
    counter: "اقتراح بديل",
    decline: "لا يناسبني",
    declineTitle: "لا بأس، أخبرنا إن شئت",
    declineBody: "ردّك لا يترتب عليه أي إجراء ضدك. سيتواصل معك مسؤول حالتك للبحث عن خيار آخر يناسبك.",
    declineReason: "ما الذي لا يناسبك؟",
    declineSend: "إرسال الرد",
    declineCancel: "رجوع للعرض",
    expiredTitle: "انتهت صلاحية هذا العرض",
    expiredBody: "لا تقلق، يمكنك طلب عرض جديد وسيتواصل معك مسؤول حالتك.",
    requestNew: "طلب عرض جديد",
    requestNewBody: (v: number) => `انتهت صلاحية العرض (v${v}). أرغب في عرض جديد.`,
    requestNewSent: "وصل طلبك إلى مسؤول حالتك، وسيرد عليك خلال يوم عمل.",
    countered: "وصل اقتراحك البديل على هذا العرض، وسنرد عليك خلال 3 أيام عمل.",
    declined: "سجّلنا ردك على هذا العرض. سيتواصل معك مسؤول حالتك للبحث عن خيار آخر.",
    accepted: "وافقت على هذا العرض.",
    viewAgreement: "تفاصيل الاتفاق",
    withdrawn: "لم يعد هذا العرض قائماً. سيتواصل معك مسؤول حالتك.",
    messages: "مراسلة مسؤول حالتك",
  },

  counter: {
    title: "اقتراح بديل",
    intro: "أخبرنا بما يناسبك. سيُراجَع اقتراحك، وقد يُقبل أو يُعدَّل، وسنرد خلال 3 أيام عمل.",
    legend: "ما الذي تود تغييره؟",
    day: "يوم القسط في الشهر",
    start: "موعد أول قسط",
    amount: "مبلغ القسط",
    dayLabel: "اليوم المناسب",
    startLabel: "البدء من",
    amountLabel: "المبلغ المناسب شهرياً",
    choose: "اختر",
    reason: "سبب الطلب",
    submit: "إرسال الاقتراح",
    needChange: "اختر ما تود تغييره وحدّد القيمة الجديدة.",
    note: "يُنشئ طلباً وليس اتفاقاً.",
    doneTitle: "وصل اقتراحك",
    replyBy: "نرد عليك قبل",
  },

  consent: {
    title: "قبل أن توافق",
    doneTitle: "تمت الموافقة",
    youAgree: "أنت توافق على:",
    fullTerms: "قراءة الشروط كاملة",
    fullTermsTitle: "شروط العرض كاملة",
    ackTerms: "قرأت الشروط وفهمت ما يحدث إذا تأخرت.",
    ackVoluntary: "أوافق باختياري، ويمكنني طلب المساعدة أو الاعتراض لاحقاً.",
    ackRequired: "يجب تأكيد الإقرارين قبل الموافقة.",
    sendCode: "إرسال الرمز",
    codeSentTo: "أرسلنا رمز التأكيد إلى جوالك",
    codeLabel: "رمز التأكيد المرسل إلى جوالك",
    resendIn: (t: string) => `يمكنك طلب رمز جديد بعد ${t}`,
    resend: "إرسال رمز جديد",
    codeRequired: "أدخل الرمز المكوّن من 6 أرقام.",
    wrongCode: (left: number) =>
      left === 1 ? "الرمز غير صحيح. تبقّت محاولة واحدة." : left === 2 ? "الرمز غير صحيح. تبقّت محاولتان." : `الرمز غير صحيح. تبقّت ${left} محاولات.`,
    agree: "أوافق على العرض",
    recording: "جارٍ تسجيل موافقتك",
    notSignature: "هذا سجل موافقة داخل المنصة برمز تحقق، وليس توقيعاً إلكترونياً مرخّصاً.",
    thanks: "شكراً، سجّلنا موافقتك",
    reference: "رقم المرجع",
    downloadCopy: "تنزيل نسخة الاتفاق",
    alreadyAccepted: "سجّلنا موافقتك على هذا العرض من قبل.",
    notOpen: "لا يمكن قبول هذا العرض الآن.",
    backToOffer: "العودة للعرض",
  },

  agreement: {
    title: "الاتفاق",
    heading: "اتفاق إعادة الجدولة",
    status: {
      PendingActivation: "بانتظار تفعيل المصرف",
      Active: "مفعّل",
      BreachReview: "قيد المتابعة مع مسؤول حالتك",
      Completed: "مكتمل",
      Terminated: "منتهٍ",
    } as Record<string, string>,
    lender: "الجهة المموّلة",
    version: "الإصدار",
    rescheduled: "المبلغ المعاد جدولته",
    waiver: "غرامات تُلغى",
    installments: "عدد الأقساط",
    installment: "القسط الشهري",
    dueDay: "يوم الاستحقاق",
    dueDayValue: (d: number) => `يوم ${d} من كل شهر`,
    start: "أول قسط",
    end: "آخر قسط",
    breach: "إذا تأخرت",
    consent: "سجل الموافقة",
    consentAt: "وقت الموافقة",
    print: "تنزيل نسخة الاتفاق",
    printHint: "اختر «حفظ بصيغة PDF» من نافذة الطباعة للاحتفاظ بنسخة.",
    emptyTitle: "لا يوجد اتفاق بعد",
    emptyBody: "بعد موافقتك على عرض يظهر الاتفاق هنا، ويمكنك تنزيل نسخة منه.",
  },

  payments: {
    title: "المدفوعات",
    next: "القسط القادم",
    nextLine: (no: number, total: number) => `القسط ${no} من ${total}`,
    on: "يوم",
    howToPay: "كيف أدفع؟",
    installment: "القسط",
    notify: "أرسلت التحويل",
    notifyTitle: (no: number) => `إشعار تحويل · القسط ${no}`,
    notifyIntro: "أخبرنا بالتحويل الذي أجريته، وسيتحقق منه المصرف.",
    transferDate: "تاريخ التحويل",
    amount: "المبلغ المحوَّل",
    reference: "مرجع التحويل",
    referenceHelp: "من إيصال البنك، إن وجد.",
    send: "إرسال الإشعار",
    dateRequired: "اختر تاريخ التحويل.",
    amountRequired: "أدخل المبلغ المحوَّل.",
    inactiveTitle: "لا يوجد جدول سداد بعد",
    allPaidTitle: "لا أقساط مستحقة الآن",
    allPaidBody: "شكراً لك. ستظهر هنا أي أقساط قادمة.",
  },

  help: {
    title: "نحن هنا للمساعدة",
    intro: "إن تغيّر وضعك، أخبرنا مبكراً. لا تحتاج لشرح كل شيء الآن.",
    legend: "ما الذي تغيّر؟",
    reasons: [
      { key: "income_loss", icon: "work_off", label: "فقدت عملي أو انخفض دخلي" },
      { key: "health", icon: "medical_services", label: "ظرف صحي" },
      { key: "family", icon: "family_restroom", label: "تغيّر في الأسرة" },
      { key: "other", icon: "more_horiz", label: "سبب آخر" },
      { key: "prefer_not_say", icon: "do_not_disturb_on", label: "أفضل ألا أذكر السبب" },
    ],
    optionalNote: "اختيار السبب اختياري.",
    call: "اطلب مكالمة من مسؤول حالتك",
    privacy: "ما تشاركه يُستخدم فقط لإيجاد حل مناسب، ويراه فريق حالتك فقط.",
    doneTitle: "وصل طلبك",
    more: "طرق أخرى للمساعدة",
    messages: "مراسلة مسؤول حالتك",
    complaint: "تقديم شكوى أو اعتراض",
    complaints: "متابعة شكاواي",
  },

  messages: {
    title: "الرسائل",
    sub: (withName: string | null, lender: string) => [withName ? `مع ${withName}` : null, lender].filter(Boolean).join(" · "),
    call: "مكالمة",
    visit: "زيارة",
    confirm: "تأكيد الحضور",
    reschedule: "إعادة الجدولة",
    rescheduleTitle: "طلب إعادة جدولة الموعد",
    rescheduleBody: "سنبلغ مسؤول حالتك ليقترح موعداً آخر يناسبك.",
    rescheduleNote: "ما الوقت الذي يناسبك؟",
    rescheduleSend: "إرسال الطلب",
    confirmed: "أكّدنا حضورك للموعد.",
    rescheduled: "أرسلنا طلب إعادة الجدولة إلى مسؤول حالتك.",
    you: "أنت",
    read: "قُرئت",
    placeholder: "اكتب رسالتك…",
    label: "رسالتك",
    send: "إرسال",
    sent: "أُرسلت رسالتك.",
    emptyTitle: "لا رسائل بعد",
    emptyBody: "اكتب لمسؤول حالتك أي سؤال، وسيرد عليك.",
    log: "المحادثة مع مسؤول حالتك",
    appointments: "المواعيد",
  },

  complaint: {
    title: "شكوى أو اعتراض",
    intro: "تراجع شكواك جهة مستقلة عن فريق حالتك، ونرد عليك كتابياً خلال 5 أيام عمل.",
    legend: "نوع الطلب",
    complaint: "شكوى على طريقة التعامل",
    objection: "اعتراض على مبلغ أو قرار",
    body: "اشرح لنا ما حدث",
    bodyRequired: "اشرح لنا ما حدث (10 أحرف على الأقل).",
    submit: "إرسال",
    regulator: "يحق لك أيضاً التقدم للجهات الرقابية المختصة في أي وقت.",
    doneTitle: "وصلت شكواك",
    reference: "رقم الشكوى",
    dueOn: "موعد الرد",
    track: "متابعة شكاواي",
    listTitle: "شكاواي واعتراضاتي",
    new: "تقديم شكوى أو اعتراض",
    emptyTitle: "لم تقدّم أي شكوى",
    emptyBody: "إن لم يعجبك شيء في طريقة التعامل أو رأيت خطأ في مبلغ، أخبرنا وستراجعه جهة مستقلة.",
    submitted: "قُدّمت في",
    response: "الرد المكتوب",
    type: { Complaint: "شكوى", Objection: "اعتراض", Appeal: "تظلّم" } as Record<string, string>,
    status: {
      Received: "استلمناها",
      InReview: "قيد المراجعة المستقلة",
      AwaitingOwner: "بانتظار ردك",
      Resolved: "تم الرد",
      Escalated: "قيد المراجعة الأعلى",
      Closed: "مغلقة",
    } as Record<string, string>,
  },

  closure: {
    closedTitle: "أُغلقت حالتك",
    closedBody: "اكتملت التسوية في",
    closedBodyTail: ". هذه مستنداتك، احتفظ بنسخة منها.",
    download: (title: string) => `تنزيل ${title}`,
    preparing: "قيد التجهيز",
    access: "يبقى حسابك متاحاً للقراءة حتى",
    accessTail: ". يمكنك طلب نسخة لاحقاً من المصرف.",
    openTitle: "حالتك ما زالت قائمة",
    openBody: "عند اكتمال التسوية وإغلاق حالتك تظهر هنا مستندات الإغلاق لتنزيلها.",
    noDocs: "نجهّز مستندات الإغلاق، وسنخبرك عند توفرها.",
  },

  notifications: {
    title: "الإشعارات",
    markAll: "تعليم الكل كمقروء",
    unread: "جديد",
    emptyTitle: "لا إشعارات",
    emptyBody: "سنخبرك هنا بكل جديد في حالتك.",
    open: "فتح",
  },

  stages: ["التعرف على حالتك", "التحقق والتقييم", "اختيار الحل المناسب", "الاتفاق", "السداد والإغلاق"],
};

export type OwnerCopy = typeof ar;

const en: OwnerCopy = {
  unit: "SAR",
  back: "Back",
  backHome: "Back to home",
  needHelp: "I need help",
  tryAgain: "Try again",
  sending: "Sending",
  networkError: "We couldn't connect. Check your internet and try again — nothing you typed is lost.",
  offlineError: "You're offline right now. Try again when you're back online.",
  genericError: "Something unexpected happened. Please try again shortly.",
  optional: "(optional)",
  close: "Close",
  daysLeft: (n: string) => `(${n})`,

  home: {
    title: "Home",
    nextStepEyebrow: "Your next step",
    until: "You have until",
    today: "(today)",
    passed: "The deadline has passed — message your case manager and we'll help",
    nothingTitle: "Nothing is needed from you right now",
    nothingBody: "We'll let you know as soon as there's a new step. You can message your case manager at any time.",
    progressTitle: "Where your case is",
    allStages: "All stages",
    progressLabel: (cur: number, total: number, label: string) => `${cur} of ${total} · ${label}`,
    docsTile: "Documents",
    debtTile: "Your balance",
    message: (name: string) => `Message ${name}`,
    messageShort: "Message",
    noManager: "A case manager will be assigned to you soon. You can message us now.",
    messages: "Messages",
    switchLanguage: "العربية",
    localizeNext: true,
    nextTitles: { offer: "Review the new offer", document: "Upload a requested document", agreement: "We recorded your consent", payment: "Your next installment", closed: "Your case is closed" },
    nextCtas: { offer: "See details", document: "Documents", agreement: "Agreement details", payment: "Payments", closed: "Closure documents" },
    docsNeed: (n: number) => `${n} to upload`,
    docsDone: "All complete",
    debtSub: "A clear breakdown",
    managerRole: "your case manager",
    appointmentCall: "Your call",
    appointmentVisit: "Your appointment",
  },

  journey: { title: "Your case stages", now: "Now" },

  docs: {
    title: "Requested documents",
    subRejected: (n: number) => `${n} to upload again`,
    subNeeded: (n: number) => `${n} to upload`,
    subDone: "All complete",
    whyAgain: "Why do we need it again?",
    until: "By",
    requestedBy: (by: string) => `Requested by ${by}`,
    upload: "Upload file",
    camera: "Take photo",
    help: "I need help with this document",
    helpSent: "Your request reached your case manager, who will reply in Messages.",
    openMessages: "Open messages",
    uploading: "Uploading",
    uploaded: (title: string) => `We received “${title}”. It is now being reviewed.`,
    tooLarge: "The file is larger than 20 MB. Try a smaller file or a lighter photo.",
    fileHint: "PDF or photo, up to 20 MB.",
    emptyTitle: "No documents are needed from you now",
    emptyBody: "If we need a document, we'll tell you why and by when.",
    closureLink: "Closure documents",
  },

  debt: {
    title: "What you owe now",
    total: "Remaining on the financing",
    report: "I think the amount is wrong",
    emptyTitle: "We haven't received your balance yet",
    emptyBody: "It will appear here once the bank sends it, with the update date and a plain explanation of each item.",
  },

  options: {
    title: "Options available to you",
    details: "See details",
    others: "Other options you can ask about",
    noOffer: "There is no offer for you right now. It will appear here once the bank sends it, and you can ask about any option below.",
    inquiryNote: "Asking doesn't commit you to anything.",
  },

  offer: {
    title: "Your offer",
    validUntil: "Valid until",
    heroInstallment: "Your new installment",
    heroPayoff: "Amount to pay",
    heroSub: (day: number, months: number) => `Day ${day} of each month · ${months} months`,
    heroPayoffSub: "One payment and the debt is settled",
    starts: "Starts",
    ends: "Ends",
    lateFees: "Late fees",
    waived: (amount: string) => `Waived (SAR ${amount})`,
    home: "Your home",
    homeStays: "Stays yours",
    whatIfLate: "What if I miss an installment?",
    lateBody: (missed: string, cure: string) =>
      `We contact you first. If ${missed} are missed, we give you ${cure} to catch up and look for a solution with you before any other step.`,
    missedTwo: "two installments in a row",
    missedN: (n: number) => `${n} installments in a row`,
    missedOne: "one installment",
    reviewAccept: "Review and accept",
    counter: "Suggest a change",
    decline: "This doesn't suit me",
    declineTitle: "That's fine — tell us if you like",
    declineBody: "Your answer won't lead to any action against you. Your case manager will contact you to find another option.",
    declineReason: "What doesn't suit you?",
    declineSend: "Send answer",
    declineCancel: "Back to the offer",
    expiredTitle: "This offer has expired",
    expiredBody: "Don't worry — you can ask for a new offer and your case manager will contact you.",
    requestNew: "Ask for a new offer",
    requestNewBody: (v: number) => `انتهت صلاحية العرض (v${v}). أرغب في عرض جديد.`,
    requestNewSent: "Your request reached your case manager, who will reply within one business day.",
    countered: "Your suggested change reached us. We'll reply within 3 business days.",
    declined: "We recorded your answer. Your case manager will contact you to find another option.",
    accepted: "You accepted this offer.",
    viewAgreement: "Agreement details",
    withdrawn: "This offer is no longer open. Your case manager will contact you.",
    messages: "Message your case manager",
  },

  counter: {
    title: "Suggest a change",
    intro: "Tell us what works for you. Your suggestion will be reviewed and may be accepted or adjusted; we'll reply within 3 business days.",
    legend: "What would you like to change?",
    day: "Day of the month",
    start: "First installment date",
    amount: "Installment amount",
    dayLabel: "Preferred day",
    startLabel: "Start from",
    amountLabel: "Preferred monthly amount",
    choose: "Choose",
    reason: "Reason",
    submit: "Send suggestion",
    needChange: "Choose what you'd like to change and set the new value.",
    note: "This creates a request, not an agreement.",
    doneTitle: "Your suggestion reached us",
    replyBy: "We'll reply by",
  },

  consent: {
    title: "Before you agree",
    doneTitle: "Agreed",
    youAgree: "You are agreeing to:",
    fullTerms: "Read the full terms",
    fullTermsTitle: "Full offer terms",
    ackTerms: "I have read the terms and understand what happens if I pay late.",
    ackVoluntary: "I agree by my own choice, and I can ask for help or object later.",
    ackRequired: "Please confirm both statements before agreeing.",
    sendCode: "Send the code",
    codeSentTo: "We sent a confirmation code to your phone",
    codeLabel: "Confirmation code sent to your phone",
    resendIn: (t: string) => `You can request a new code in ${t}`,
    resend: "Send a new code",
    codeRequired: "Enter the 6-digit code.",
    wrongCode: (left: number) => (left === 1 ? "Incorrect code. 1 attempt left." : `Incorrect code. ${left} attempts left.`),
    agree: "I agree to the offer",
    recording: "Recording your consent",
    notSignature: "This is an in-platform consent record confirmed by a one-time code — not a licensed electronic signature.",
    thanks: "Thank you — we recorded your consent",
    reference: "Reference number",
    downloadCopy: "Download a copy of the agreement",
    alreadyAccepted: "You already agreed to this offer.",
    notOpen: "This offer can't be accepted right now.",
    backToOffer: "Back to the offer",
  },

  agreement: {
    title: "Agreement",
    heading: "Rescheduling agreement",
    status: {
      PendingActivation: "Awaiting activation by the bank",
      Active: "Active",
      BreachReview: "Being followed up with your case manager",
      Completed: "Completed",
      Terminated: "Ended",
    },
    lender: "Financing institution",
    version: "Version",
    rescheduled: "Rescheduled amount",
    waiver: "Late fees waived",
    installments: "Number of installments",
    installment: "Monthly installment",
    dueDay: "Due day",
    dueDayValue: (d: number) => `Day ${d} of each month`,
    start: "First installment",
    end: "Last installment",
    breach: "If you pay late",
    consent: "Consent record",
    consentAt: "Consent time",
    print: "Download a copy of the agreement",
    printHint: "Choose “Save as PDF” in the print window to keep a copy.",
    emptyTitle: "No agreement yet",
    emptyBody: "Once you accept an offer, the agreement appears here and you can download a copy.",
  },

  payments: {
    title: "Payments",
    next: "Next installment",
    nextLine: (no: number, total: number) => `Installment ${no} of ${total}`,
    on: "Due",
    howToPay: "How do I pay?",
    installment: "Installment",
    notify: "I made the transfer",
    notifyTitle: (no: number) => `Transfer notice · installment ${no}`,
    notifyIntro: "Tell us about the transfer you made, and the bank will verify it.",
    transferDate: "Transfer date",
    amount: "Amount transferred",
    reference: "Transfer reference",
    referenceHelp: "From your bank receipt, if you have one.",
    send: "Send notice",
    dateRequired: "Choose the transfer date.",
    amountRequired: "Enter the amount transferred.",
    inactiveTitle: "No payment schedule yet",
    allPaidTitle: "No installments due now",
    allPaidBody: "Thank you. Any upcoming installments will appear here.",
  },

  help: {
    title: "We're here to help",
    intro: "If your situation has changed, tell us early. You don't need to explain everything now.",
    legend: "What changed?",
    reasons: [
      { key: "income_loss", icon: "work_off", label: "I lost my job or my income dropped" },
      { key: "health", icon: "medical_services", label: "A health matter" },
      { key: "family", icon: "family_restroom", label: "A change in my family" },
      { key: "other", icon: "more_horiz", label: "Another reason" },
      { key: "prefer_not_say", icon: "do_not_disturb_on", label: "I'd rather not say" },
    ],
    optionalNote: "Choosing a reason is optional.",
    call: "Ask your case manager to call you",
    privacy: "What you share is used only to find a suitable solution, and only your case team sees it.",
    doneTitle: "Your request reached us",
    more: "Other ways to get help",
    messages: "Message your case manager",
    complaint: "Make a complaint or objection",
    complaints: "Track my complaints",
  },

  messages: {
    title: "Messages",
    sub: (withName: string | null, lender: string) => [withName ? `With ${withName}` : null, lender].filter(Boolean).join(" · "),
    call: "Call",
    visit: "Visit",
    confirm: "Confirm attendance",
    reschedule: "Reschedule",
    rescheduleTitle: "Ask to reschedule",
    rescheduleBody: "We'll let your case manager know so they can suggest another time.",
    rescheduleNote: "What time suits you?",
    rescheduleSend: "Send request",
    confirmed: "We confirmed your attendance.",
    rescheduled: "We sent your reschedule request to your case manager.",
    you: "You",
    read: "Read",
    placeholder: "Write your message…",
    label: "Your message",
    send: "Send",
    sent: "Your message was sent.",
    emptyTitle: "No messages yet",
    emptyBody: "Write any question to your case manager and they'll reply.",
    log: "Conversation with your case manager",
    appointments: "Appointments",
  },

  complaint: {
    title: "Complaint or objection",
    intro: "A reviewer independent of your case team handles your complaint, and we reply in writing within 5 business days.",
    legend: "Type of request",
    complaint: "A complaint about how I was treated",
    objection: "An objection to an amount or decision",
    body: "Tell us what happened",
    bodyRequired: "Tell us what happened (at least 10 characters).",
    submit: "Send",
    regulator: "You also have the right to go to the competent regulatory authorities at any time.",
    doneTitle: "Your complaint reached us",
    reference: "Complaint number",
    dueOn: "Reply due",
    track: "Track my complaints",
    listTitle: "My complaints and objections",
    new: "Make a complaint or objection",
    emptyTitle: "You haven't made any complaints",
    emptyBody: "If something about how you were treated wasn't right, or you see a wrong amount, tell us and an independent reviewer will look at it.",
    submitted: "Submitted",
    response: "Written reply",
    type: { Complaint: "Complaint", Objection: "Objection", Appeal: "Appeal" },
    status: {
      Received: "Received",
      InReview: "Under independent review",
      AwaitingOwner: "Waiting for your reply",
      Resolved: "Replied",
      Escalated: "Under senior review",
      Closed: "Closed",
    },
  },

  closure: {
    closedTitle: "Your case is closed",
    closedBody: "The settlement was completed on",
    closedBodyTail: ". These are your documents — keep a copy.",
    download: (title: string) => `Download ${title}`,
    preparing: "Being prepared",
    access: "Your account stays readable until",
    accessTail: ". You can ask the bank for a copy later.",
    openTitle: "Your case is still open",
    openBody: "Once the settlement is complete and your case is closed, your closure documents will appear here.",
    noDocs: "We're preparing your closure documents and will let you know when they're ready.",
  },

  notifications: {
    title: "Notifications",
    markAll: "Mark all as read",
    unread: "New",
    emptyTitle: "No notifications",
    emptyBody: "We'll tell you here about anything new in your case.",
    open: "Open",
  },

  stages: ["Getting to know your case", "Verification and valuation", "Choosing the right solution", "The agreement", "Payment and closure"],
};

export function ownerCopy(locale: Locale): OwnerCopy {
  return locale === "en" ? en : ar;
}
