import type { Locale } from "@/lib/i18n";

/*
 * «فريق رهون» workspace copy (Phase 1A step 6, design request D-4 — «نص مقترح», «بانتظار اعتماد التصميم»).
 * Coordination wording is provisional (V2); coordination is not formal representation (V1). Internal timers are
 * labelled internal and never shown to the individual (V5).
 */

export type TeamStatusKey =
  | "submitted"
  | "team_review"
  | "info_requested"
  | "lender_coordination"
  | "offer_available"
  | "response_recorded"
  | "closed"
  | "not_eligible"
  | "withdrawn";

const ar = {
  brand: "فريق رهون",
  nav: {
    label: "تنقل فريق رهون",
    requests: "الطلبات",
    verify: "بحاجة إلى تحقق",
    objections: "الاعتراضات والشكاوى",
  },
  signOut: "تسجيل الخروج",
  internal: "داخلي — لا يظهر للعميل",
  genericError: "حدث خطأ غير متوقع. حاول مرة أخرى بعد قليل.",
  networkError: "تعذّر الاتصال. تحقق من الإنترنت ثم حاول مرة أخرى.",
  cancel: "إلغاء",
  save: "حفظ",
  send: "إرسال",

  status: {
    submitted: "مقدَّم",
    team_review: "قيد الدراسة",
    info_requested: "بانتظار معلومة من العميل",
    lender_coordination: "قيد التنسيق مع الجهة",
    offer_available: "عرض منشور للعميل",
    response_recorded: "رد العميل مسجل",
    closed: "مغلق",
    not_eligible: "غير مناسب للخدمة",
    withdrawn: "مسحوب",
  } satisfies Record<TeamStatusKey, string>,
  waiting: { team: "فريق رهون", applicant: "العميل", lender: "الجهة الممولة", none: "—" } as Record<string, string>,

  queue: {
    title: "الطلبات",
    sub: "طلبات الأفراد لمعالجة تعثر التمويل العقاري",
    tabs: { mine: "مسندة إليّ", unassigned: "غير مسندة", all: "الكل", closed: "المنتهية" },
    tabsLabel: "تصفية الطلبات",
    cols: {
      ref: "المرجع",
      applicant: "مقدم الطلب",
      lender: "الجهة الممولة",
      status: "الحالة",
      waiting: "ننتظر",
      updated: "آخر تحديث",
      assigned: "المسند إليه",
      timer: "المدة في الحالة",
    },
    days: (n: number) => (n === 0 ? "اليوم" : n === 1 ? "يوم" : n === 2 ? "يومان" : n <= 10 ? `${n} أيام` : `${n} يوماً`),
    timerLevel: { ok: "ضمن المعتاد", warn: "تجاوز المعتاد", alert: "متأخر", none: "—" } as Record<string, string>,
    emptyTitle: "لا توجد طلبات هنا",
    emptyBody: "ستظهر هنا الطلبات بحسب التبويب المختار.",
    unassigned: "غير مسند",
    open: "فتح",
  },

  review: {
    back: "الطلبات",
    assignedTo: "المسند إليه",
    notAssigned: "غير مسند",
    take: "استلام الطلب",
    assign: "إسناد…",
    assignTitle: "إسناد الطلب",
    assignTo: "العضو",
    assignPick: "اختر عضواً",
    declared: "ما صرّح به العميل",
    sourceClient: "المصدر: العميل · تقريبي",
    applicant: "مقدم الطلب",
    idLabel: "الهوية",
    phoneLabel: "الجوال",
    identity: "التحقق من الهوية",
    identitySelf: "مُعلنة من العميل ولم يُتحقق منها",
    identityChecked: (by: string) => `تحقق منها ${by}`,
    identityCheck: "تسجيل التحقق من الهوية…",
    identityTitle: "التحقق من هوية العميل",
    identityNote: "كيف تحققت؟",
    identityHelp: "مثلاً: مطابقة صورة الهوية مع الاسم ورقم الجوال، أو مطابقة بيانات الجهة الممولة. مطلوب قبل أي تنسيق (V12).",
    lender: "الجهة الممولة",
    lenderOther: "جهة غير مدرجة (كتبها العميل)",
    contract: "رقم العقد",
    installment: "القسط الشهري",
    arrears: "مدة التأخر",
    city: "مدينة العقار",
    preference: "ما يناسب العميل",
    affordable: "يستطيع دفعه شهرياً",
    words: "بكلمات العميل",
    duplicateOf: (ref: string) => `أكّد العميل أنه لتمويل مختلف عن طلبه ${ref}`,
    documents: "المستندات",
    noDocuments: "لا مستندات",
    teamOnly: "داخلي",
    visibleToClient: "يظهر للعميل",
    addedLater: "بعد الإرسال",
    uploadDoc: "رفع مستند…",
    uploadTitle: "رفع مستند للطلب",
    docKind: "النوع",
    docKinds: { lender_letter: "خطاب الجهة الممولة", coordination_evidence: "مرفق تنسيق", identity_evidence: "إثبات هوية", other: "مستند آخر" } as Record<string, string>,
    docName: "اسم المستند",
    docFile: "الملف",
    docVisible: "يظهر للعميل",
    consent: "دليل الموافقة",
    consentActive: "موافقة سارية",
    consentNone: "لا توجد موافقة سارية — التنسيق موقوف",
    consentRecipient: "الجهة المسماة",
    consentVersion: "إصدار النص",
    consentAt: "وقت التأكيد برمز الجوال",
    consentWithdrawn: "سُحبت",
    consentReasons: { withdrawn_by_applicant: "سحبها العميل", recipient_changed: "تغيّرت الجهة", request_withdrawn: "سُحب الطلب", superseded: "استُبدلت بموافقة أحدث" } as Record<string, string>,
    consentHistory: "السجل",
    actions: "الإجراءات",
    actionKeys: {
      pick_up: "بدء دراسة الطلب",
      request_info: "طلب استكمال…",
      start_coordination: "بدء التنسيق مع الجهة",
      not_eligible: "غير مناسب للخدمة…",
      close: "إغلاق الطلب…",
      continue_coordination: "متابعة التنسيق",
      reopen: "إعادة فتح الدراسة…",
    } as Record<string, string>,
    whatClientSees: "ما سيراه العميل",
    clientStatus: "الحالة",
    clientWaiting: "ننتظر",
    clientNext: "الخطوة التالية",
    defaultNext: "(النص الافتراضي للحالة)",
    timer: "مؤشر المدة",
    timerText: (inStatus: string, since: string | null) => (since ? `في الحالة منذ ${inStatus} · منذ الإرسال ${since}` : `في الحالة منذ ${inStatus}`),
    tabs: { coordination: "سجل التنسيق", timeline: "الخط الزمني", messages: "الرسائل" },
    tabsLabel: "أقسام الطلب",
  },

  info: {
    title: "طلب استكمال من العميل",
    items: "ما نحتاجه",
    itemsHelp: "بند في كل سطر، مثل: كشف حساب آخر 3 أشهر.",
    message: "رسالة للعميل",
    messageHelp: "اشرح بلغة بسيطة ما تحتاجه ولماذا. تظهر كخطوة تالية للعميل، دون أي مهلة.",
    preview: "ما سيراه العميل",
    submit: "إرسال الطلب للعميل",
  },

  coordination: {
    title: "سجل التنسيق مع الجهة الممولة",
    banner: "التنسيق لا يعني تمثيلاً رسمياً للعميل. نشارك البيانات التي وافق عليها العميل وننقل ما يصلنا فقط (V1). صيغة السجل مبدئية (V2).",
    add: "إضافة قيد…",
    addTitle: "قيد جديد في سجل التنسيق",
    correct: "تصحيح…",
    correctTitle: "تصحيح قيد (قيد جديد يشير إلى الأصل)",
    corrects: "تصحيح لقيد سابق",
    channel: "القناة",
    channels: { phone: "هاتف", email: "بريد إلكتروني", letter: "خطاب رسمي", visit: "زيارة", other: "أخرى" } as Record<string, string>,
    kind: "نوع القيد",
    kinds: { general: "تواصل", lender_response: "رد من الجهة", offer_received: "استلام عرض", response_relay: "نقل رد العميل" } as Record<string, string>,
    occurredAt: "التاريخ والوقت",
    counterpart: "الطرف لدى الجهة",
    counterpartHelp: "الاسم أو الصفة كما ذُكر.",
    summary: "الملخص",
    evidence: "المرفقات",
    evidenceHelp: "اختر من مستندات الطلب (ارفع خطاب الجهة أو المرفق أولاً من قسم المستندات).",
    visible: "يظهر للعميل؟",
    visibleHelp: "مغلق افتراضياً. عند التفعيل يظهر للعميل النص أدناه فقط، لا الملخص الداخلي.",
    applicantText: "النص الذي يراه العميل",
    empty: "لا توجد قيود بعد.",
    recordedBy: (name: string) => `سجّله ${name}`,
    consentBlocked: "لا يمكن التنسيق دون موافقة سارية من العميل.",
  },

  messages: {
    title: "الرسائل مع العميل",
    empty: "لا رسائل بعد.",
    toClient: "رسالة للعميل",
    note: "ملاحظة داخلية",
    noteHelp: "لا تظهر للعميل أبداً.",
    internalTag: "ملاحظة داخلية",
    fromClient: "العميل",
    fromTeam: "فريق رهون",
    sendMessage: "إرسال للعميل",
    addNote: "حفظ الملاحظة",
  },

  update: {
    button: "تحديث للعميل…",
    title: "نشر تحديث للعميل",
    text: "التحديث",
    nextStep: "الخطوة التالية كما يراها العميل",
    nextHelp: "اختياري. بلغة بسيطة ودون أي تاريخ أو وعد.",
    submit: "نشر التحديث",
  },

  notEligible: {
    title: "غير مناسب للخدمة حالياً",
    reason: "السبب كما سيراه العميل",
    help: "بلغة واضحة ودون لوم. التصنيف المؤقت: «خارج نطاق الخدمة» (Q4). يمكن للعميل الاعتراض.",
    submit: "تأكيد",
  },

  pickUp: { nextStep: "الخطوة التالية للعميل (اختياري)" },
  concerns: {
    title: "الاعتراضات والشكاوى",
    sub: "اعتراضات الأفراد على البيانات أو المبالغ أو القرارات، وشكاواهم على الخدمة (معالجة العقبات).",
    tabs: { open: "مفتوحة", answered: "تم الرد" },
    tabsLabel: "تصفية",
    empty: "لا يوجد شيء هنا.",
    kinds: { objection: "اعتراض", complaint: "شكوى" } as Record<string, string>,
    subjects: { data: "بيانات", amount: "مبلغ", decision: "قرار", service: "الخدمة", other: "أخرى" } as Record<string, string>,
    answer: "الرد…",
    answerTitle: "الرد على العميل",
    outcome: "نتيجة المراجعة",
    outcomes: { upheld: "قُبل", not_upheld: "لم يُقبل", clarified: "توضيح" } as Record<string, string>,
    response: "الرد كما سيراه العميل",
    responseHelp: "بلغة واضحة ودون وعد بمدة أو نتيجة.",
    notYou: "يرد عضو آخر (أنت منسق هذا الطلب)",
    daysOpen: (n: string) => `مفتوح منذ ${n}`,
    request: "الطلب",
    answeredBy: (name: string) => `رد ${name}`,
    section: "اعتراضات وشكاوى على هذا الطلب",
  },
  referral: {
    button: "إحالة لمختص…",
    title: "تسجيل إحالة إلى مختص",
    banner: "سجل يدوي: من هم المختصون وكيف تتم الإحالة ما زال يحتاج تحققاً (V9). لا تعني الإحالة تمثيلاً للعميل (V1).",
    type: "نوع المختص",
    types: { legal: "قانوني", financial_counselling: "استشارة مالية", social_support: "دعم اجتماعي", other: "أخرى" } as Record<string, string>,
    name: "المختص أو الجهة",
    note: "ملاحظة داخلية",
    applicantText: "ما سيراه العميل",
    section: "الإحالات",
  },
  reopen: {
    title: "إعادة فتح الدراسة",
    reason: "السبب",
    help: "بعد قبول اعتراض العميل على قرار «غير مناسب للخدمة».",
    submit: "إعادة الفتح",
  },

  offers: {
    title: "عروض الجهة",
    empty: "لم يُسجَّل عرض بعد.",
    record: "تسجيل عرض الجهة…",
    recordTitle: "تسجيل عرض الجهة من خطابها",
    status: { pendingverification: "بانتظار التحقق", returned: "أُعيد للتصحيح", published: "منشور للعميل", superseded: "مستبدل" } as Record<string, string>,
    version: (n: number) => `الإصدار ${n}`,
    recordedBy: (name: string) => `سجّله ${name}`,
    verifiedBy: (name: string) => `تحقق منه ${name}`,
    returnReason: "سبب الإعادة",
    letter: "خطاب الجهة (إلزامي)",
    letterPick: "اختر خطاب الجهة",
    letterHelp: "ارفع الخطاب أولاً من قسم المستندات بنوع «خطاب الجهة الممولة».",
    path: "المسار",
    paths: { p1: "الاحتفاظ بالعقار (P1)", p2: "تسوية المديونية (P2)", p3: "البيع الرضائي (P3)" } as Record<string, string>,
    newInstallment: "القسط الجديد",
    termMonths: "المدة بالأشهر",
    startText: "البدء (كما في الخطاب)",
    settlementAmount: "مبلغ التسوية",
    paymentConditions: "شروط السداد",
    remainingText: "ما يُفك أو يتبقى",
    saleTerms: "شروط تنسيق البيع",
    conditions: "شروط أخرى",
    effectText: "«أثره عليك» — بلغة يفهمها العميل",
    lenderReference: "مرجع خطاب الجهة",
    lenderLetterDate: "تاريخ خطاب الجهة",
    validity: "الصلاحية كما في الخطاب (اختياري)",
    validityHelp: "تُعرض للعميل كشرط من الجهة «بحسب خطاب الجهة»، لا كمهلة من رهون.",
    shareLetter: "إتاحة خطاب الجهة للعميل",
    submit: "إرسال للتحقق",
    sameMemberNote: "يتحقق من العرض عضو آخر من الفريق.",
  },
  verify: {
    title: "بحاجة إلى تحقق",
    sub: "عروض سجّلها الفريق من خطابات الجهات وتنتظر مطابقة عضو آخر قبل نشرها للعميل.",
    empty: "لا توجد عروض بانتظار التحقق.",
    panel: "التحقق من العرض",
    source: "المصدر: خطاب الجهة",
    openLetter: "فتح خطاب الجهة",
    checklist: "قائمة المطابقة",
    items: {
      amounts_match_letter: "المبالغ مطابقة للخطاب",
      terms_match_letter: "المسار والشروط مطابقة للخطاب",
      reference_and_date_match: "المرجع والتاريخ مطابقان",
      effect_text_accurate: "«أثره عليك» دقيق وغير مضلل",
    } as Record<string, string>,
    publish: "اعتماد ونشر للعميل",
    return: "إعادة مع سبب…",
    returnTitle: "إعادة العرض لمن سجّله",
    reason: "السبب",
    recordedByYou: "سجّلته أنت — يتحقق منه عضو آخر",
    open: "فتح",
  },
  responses: {
    title: "رد العميل",
    kinds: { accept: "موافقة", decline: "لا يناسبه", question: "سؤال", counter: "اقتراح" } as Record<string, string>,
    otp: "مؤكدة برمز الجوال",
    relayed: "نُقل للجهة",
    notRelayed: "لم يُنقل بعد",
    relay: "تسجيل نقل الرد للجهة…",
    relayTitle: "نقل رد العميل إلى الجهة الممولة",
    applicantText: "ما سيراه العميل (اختياري)",
    applicantTextHelp: "افتراضياً: «نقلنا ردك إلى جهتك الممولة، وسنبلغك بالخطوة التالية.»",
  },
  close: {
    title: "إغلاق الطلب",
    outcome: "النتيجة",
    outcomes: { offer_accepted: "قبل العميل العرض", offer_declined: "لم يناسب العرض العميل", lender_no_offer: "ردّت الجهة دون عرض", other: "أخرى" } as Record<string, string>,
    summary: "ملخص النتيجة كما سيراه العميل",
    summaryHelp: "بلغة واضحة. عند رد الجهة دون عرض، انقل ردها كما ورد. تنفيذ أي اتفاق يُتابع لاحقاً (المرحلة 1A-2).",
    submit: "إغلاق الطلب",
  },

};

export type TeamCopy = typeof ar;

const en: TeamCopy = {
  brand: "Rahoon team",
  nav: { label: "Rahoon team navigation", requests: "Requests", verify: "Needs verification", objections: "Objections and complaints" },
  signOut: "Sign out",
  internal: "Internal — never shown to the individual",
  genericError: "Something unexpected happened. Please try again shortly.",
  networkError: "We couldn't connect. Check your internet and try again.",
  cancel: "Cancel",
  save: "Save",
  send: "Send",
  status: {
    submitted: "Submitted",
    team_review: "Under review",
    info_requested: "Waiting for the individual",
    lender_coordination: "Coordinating with the lender",
    offer_available: "Offer published to the individual",
    response_recorded: "Response recorded",
    closed: "Closed",
    not_eligible: "Not suitable",
    withdrawn: "Withdrawn",
  },
  waiting: { team: "Rahoon team", applicant: "Individual", lender: "Lender", none: "—" },
  queue: {
    title: "Requests",
    sub: "Individuals' requests about mortgage default",
    tabs: { mine: "Assigned to me", unassigned: "Unassigned", all: "All", closed: "Finished" },
    tabsLabel: "Filter requests",
    cols: { ref: "Reference", applicant: "Applicant", lender: "Lender", status: "Status", waiting: "Waiting on", updated: "Last update", assigned: "Assigned to", timer: "Time in status" },
    days: (n: number) => (n === 0 ? "today" : n === 1 ? "1 day" : `${n} days`),
    timerLevel: { ok: "Within usual", warn: "Above usual", alert: "Late", none: "—" },
    emptyTitle: "No requests here",
    emptyBody: "Requests appear here according to the selected tab.",
    unassigned: "Unassigned",
    open: "Open",
  },
  review: {
    back: "Requests",
    assignedTo: "Assigned to",
    notAssigned: "Unassigned",
    take: "Take request",
    assign: "Assign…",
    assignTitle: "Assign request",
    assignTo: "Member",
    assignPick: "Choose a member",
    declared: "What the individual declared",
    sourceClient: "Source: individual · approximate",
    applicant: "Applicant",
    idLabel: "ID",
    phoneLabel: "Mobile",
    identity: "Identity check",
    identitySelf: "Self-declared, not checked",
    identityChecked: (by: string) => `Checked by ${by}`,
    identityCheck: "Record identity check…",
    identityTitle: "Check the individual's identity",
    identityNote: "How did you check?",
    identityHelp: "For example: matching the ID copy with the name and mobile, or the lender's data. Required before any coordination (V12).",
    lender: "Lender",
    lenderOther: "Not in the list (typed by the individual)",
    contract: "Contract number",
    installment: "Monthly installment",
    arrears: "Behind for",
    city: "Property city",
    preference: "Individual's preference",
    affordable: "Can pay monthly",
    words: "In the individual's words",
    duplicateOf: (ref: string) => `The individual confirmed this is a different finance from ${ref}`,
    documents: "Documents",
    noDocuments: "No documents",
    teamOnly: "Internal",
    visibleToClient: "Visible to individual",
    addedLater: "After submission",
    uploadDoc: "Upload document…",
    uploadTitle: "Upload a document to the request",
    docKind: "Type",
    docKinds: { lender_letter: "Lender letter", coordination_evidence: "Coordination attachment", identity_evidence: "Identity evidence", other: "Other document" },
    docName: "Document name",
    docFile: "File",
    docVisible: "Visible to the individual",
    consent: "Consent evidence",
    consentActive: "Active consent",
    consentNone: "No active consent — coordination paused",
    consentRecipient: "Named lender",
    consentVersion: "Text version",
    consentAt: "Confirmed by SMS code at",
    consentWithdrawn: "Withdrawn",
    consentReasons: { withdrawn_by_applicant: "Withdrawn by the individual", recipient_changed: "Lender changed", request_withdrawn: "Request withdrawn", superseded: "Replaced by a newer consent" },
    consentHistory: "History",
    actions: "Actions",
    actionKeys: {
      pick_up: "Start review",
      request_info: "Request information…",
      start_coordination: "Start coordinating with the lender",
      not_eligible: "Not suitable…",
      close: "Close request…",
      continue_coordination: "Continue coordination",
      reopen: "Reopen the study…",
    },
    whatClientSees: "What the individual sees",
    clientStatus: "Status",
    clientWaiting: "Waiting on",
    clientNext: "Next step",
    defaultNext: "(the status's default text)",
    timer: "Time indicator",
    timerText: (inStatus: string, since: string | null) => (since ? `In status ${inStatus} · since submission ${since}` : `In status ${inStatus}`),
    tabs: { coordination: "Coordination log", timeline: "Timeline", messages: "Messages" },
    tabsLabel: "Request sections",
  },
  info: {
    title: "Request information from the individual",
    items: "What we need",
    itemsHelp: "One item per line, e.g. last 3 months' bank statement.",
    message: "Message to the individual",
    messageHelp: "Explain simply what you need and why. It shows as their next step, with no deadline.",
    preview: "What the individual sees",
    submit: "Send to the individual",
  },
  coordination: {
    title: "Coordination log with the lender",
    banner: "Coordination is not formal representation of the individual. We share only data they consented to and relay what we receive (V1). The log format is provisional (V2).",
    add: "Add entry…",
    addTitle: "New coordination entry",
    correct: "Correct…",
    correctTitle: "Correct an entry (a new entry referencing the original)",
    corrects: "Correction of an earlier entry",
    channel: "Channel",
    channels: { phone: "Phone", email: "Email", letter: "Official letter", visit: "Visit", other: "Other" },
    kind: "Entry type",
    kinds: { general: "Contact", lender_response: "Lender response", offer_received: "Offer received", response_relay: "Individual's response relayed" },
    occurredAt: "Date and time",
    counterpart: "Lender counterpart",
    counterpartHelp: "Name or role as given.",
    summary: "Summary",
    evidence: "Attachments",
    evidenceHelp: "Pick from the request's documents (upload the lender letter or attachment first).",
    visible: "Visible to the individual?",
    visibleHelp: "Off by default. When on, only the text below is shown to the individual — never the internal summary.",
    applicantText: "Text the individual sees",
    empty: "No entries yet.",
    recordedBy: (name: string) => `Recorded by ${name}`,
    consentBlocked: "Coordination isn't possible without the individual's active consent.",
  },
  messages: {
    title: "Messages with the individual",
    empty: "No messages yet.",
    toClient: "Message to the individual",
    note: "Internal note",
    noteHelp: "Never shown to the individual.",
    internalTag: "Internal note",
    fromClient: "Individual",
    fromTeam: "Rahoon team",
    sendMessage: "Send to the individual",
    addNote: "Save note",
  },
  update: {
    button: "Update for the individual…",
    title: "Publish an update to the individual",
    text: "Update",
    nextStep: "Next step as the individual sees it",
    nextHelp: "Optional. Plain language, no date or promise.",
    submit: "Publish update",
  },
  notEligible: {
    title: "Not suitable for the service right now",
    reason: "Reason as the individual will see it",
    help: "Clear and without blame. Interim category: “out of service scope” (Q4). The individual can object.",
    submit: "Confirm",
  },
  pickUp: { nextStep: "Next step for the individual (optional)" },
  concerns: {
    title: "Objections and complaints",
    sub: "Individuals' objections to data, amounts or decisions, and complaints about the service (removing obstacles).",
    tabs: { open: "Open", answered: "Answered" },
    tabsLabel: "Filter",
    empty: "Nothing here.",
    kinds: { objection: "Objection", complaint: "Complaint" },
    subjects: { data: "Data", amount: "Amount", decision: "Decision", service: "Service", other: "Other" },
    answer: "Answer…",
    answerTitle: "Answer the individual",
    outcome: "Outcome",
    outcomes: { upheld: "Upheld", not_upheld: "Not upheld", clarified: "Clarified" },
    response: "Answer as the individual sees it",
    responseHelp: "Plain language, no promised time or result.",
    notYou: "Another member answers (you coordinate this request)",
    daysOpen: (n: string) => `Open for ${n}`,
    request: "Request",
    answeredBy: (name: string) => `Answered by ${name}`,
    section: "Objections and complaints on this request",
  },
  referral: {
    button: "Refer to a specialist…",
    title: "Record a referral to a specialist",
    banner: "Manual record: who the specialists are and how referral works still needs verification (V9). A referral is not representation (V1).",
    type: "Specialist type",
    types: { legal: "Legal", financial_counselling: "Financial counselling", social_support: "Social support", other: "Other" },
    name: "Specialist or organization",
    note: "Internal note",
    applicantText: "What the individual sees",
    section: "Referrals",
  },
  reopen: {
    title: "Reopen the study",
    reason: "Reason",
    help: "After upholding the individual's objection to «not suitable».",
    submit: "Reopen",
  },

  offers: {
    title: "Lender offers",
    empty: "No offer recorded yet.",
    record: "Record lender offer…",
    recordTitle: "Record the lender's offer from its letter",
    status: { pendingverification: "Awaiting verification", returned: "Returned for correction", published: "Published", superseded: "Superseded" },
    version: (n: number) => `Version ${n}`,
    recordedBy: (name: string) => `Recorded by ${name}`,
    verifiedBy: (name: string) => `Verified by ${name}`,
    returnReason: "Return reason",
    letter: "Lender letter (required)",
    letterPick: "Choose the lender letter",
    letterHelp: "Upload the letter first in Documents with the type “Lender letter”.",
    path: "Path",
    paths: { p1: "Keep the property (P1)", p2: "Settle the debt (P2)", p3: "Consensual sale (P3)" },
    newInstallment: "New installment",
    termMonths: "Term in months",
    startText: "Start (as in the letter)",
    settlementAmount: "Settlement amount",
    paymentConditions: "Payment conditions",
    remainingText: "What is released or remains",
    saleTerms: "Sale coordination terms",
    conditions: "Other conditions",
    effectText: "“What it means for you” — in plain language",
    lenderReference: "Lender letter reference",
    lenderLetterDate: "Lender letter date",
    validity: "Validity as in the letter (optional)",
    validityHelp: "Shown to the individual as the lender's condition, never as a Rahoon deadline.",
    shareLetter: "Share the lender letter with the individual",
    submit: "Send for verification",
    sameMemberNote: "Another team member verifies the offer.",
  },
  verify: {
    title: "Needs verification",
    sub: "Offers recorded from lender letters, awaiting another member's check before publication.",
    empty: "No offers awaiting verification.",
    panel: "Verify the offer",
    source: "Source: lender letter",
    openLetter: "Open the lender letter",
    checklist: "Match checklist",
    items: {
      amounts_match_letter: "Amounts match the letter",
      terms_match_letter: "Path and terms match the letter",
      reference_and_date_match: "Reference and date match",
      effect_text_accurate: "“What it means for you” is accurate",
    },
    publish: "Approve and publish",
    return: "Return with reason…",
    returnTitle: "Return the offer to its recorder",
    reason: "Reason",
    recordedByYou: "You recorded it — another member verifies",
    open: "Open",
  },
  responses: {
    title: "Individual's response",
    kinds: { accept: "Agreed", decline: "Doesn't suit", question: "Question", counter: "Suggestion" },
    otp: "Confirmed by SMS code",
    relayed: "Relayed to the lender",
    notRelayed: "Not relayed yet",
    relay: "Record relaying to the lender…",
    relayTitle: "Relay the response to the lender",
    applicantText: "What the individual sees (optional)",
    applicantTextHelp: "Default: “We passed your response to your lender and will tell you the next step.”",
  },
  close: {
    title: "Close request",
    outcome: "Outcome",
    outcomes: { offer_accepted: "Offer accepted", offer_declined: "Offer didn't suit", lender_no_offer: "Lender answered without an offer", other: "Other" },
    summary: "Outcome summary as the individual sees it",
    summaryHelp: "Plain language. If the lender answered without an offer, quote it as received. Execution is tracked later (Phase 1A-2).",
    submit: "Close request",
  },

};

export function teamCopy(locale: Locale): TeamCopy {
  return locale === "en" ? en : ar;
}
